
#include "constants/Db_Constants.hpp"
#include "container/Download.hpp"
#include <QJsonArray>

namespace CONTAINER {
    // Public

    Download::Download() : id(-1), url(QString()), audio_code(0), video_code(0), video_format(QString()), title(QString()), save_name(QString()), file_path(QString()), suffix(QString()), progress(0), download_state(false), metadata(false), subtitles(false), auto_generated_subtitles(false) {}

    Download::Download(const int id, QString url, const int audio_code, const int video_code, QString video_format, QString title, QString save_name, QString file_path, QString suffix, const bool metadata, const bool subtitles, const bool auto_generated_subtitles) : id(id), url(std::move(url)), audio_code(audio_code), video_code(video_code), video_format(std::move(video_format)), title(std::move(title)), save_name(std::move(save_name)), file_path(std::move(file_path)), suffix(std::move(suffix)), progress(0), download_state(false), metadata(metadata), subtitles(subtitles), auto_generated_subtitles(auto_generated_subtitles) {}

    Download::Download(const int id, QString url, const int audio_code, const int video_code, QString video_format, QString title, QString save_name, QString file_path, QString suffix, const int progress, const bool download_state, const bool metadata, const bool subtitles, const bool auto_generated_subtitles) : id(id), url(std::move(url)), audio_code(audio_code), video_code(video_code), video_format(std::move(video_format)), title(std::move(title)), save_name(std::move(save_name)), file_path(std::move(file_path)), suffix(std::move(suffix)), progress(progress), download_state(download_state), metadata(metadata), subtitles(subtitles), auto_generated_subtitles(auto_generated_subtitles) {}

    Download::Download(const Download& other) : id(other.id), url(other.url), audio_code(other.audio_code), video_code(other.video_code), video_format(other.video_format), title(other.title), save_name(other.save_name), file_path(other.file_path), suffix(other.suffix), progress(other.progress), download_state(other.download_state), metadata(other.metadata), subtitles(other.subtitles), auto_generated_subtitles(other.auto_generated_subtitles) {}

    Download& Download::operator=(const Download& other) {
        if (this != &other) {
            QMutexLocker locker(&this->mutex);

            this->id = other.id;
            this->url = other.url;
            this->audio_code = other.audio_code;
            this->video_code = other.video_code;
            this->video_format = other.video_format;
            this->title = other.title;
            this->save_name = other.save_name;
            this->file_path = other.file_path;
            this->suffix = other.suffix;
            this->progress = other.progress;
            this->download_state = other.download_state;
            this->metadata = other.metadata;
            this->subtitles = other.subtitles;
            this->auto_generated_subtitles = other.auto_generated_subtitles;
        }

        return *this;
    }

    bool Download::operator==(const Download& other) const {return this->id == other.id;}

    int Download::getId() const {QMutexLocker locker(&this->mutex); return this->id;}

    QString Download::getUrl() const {QMutexLocker locker(&this->mutex); return this->url;}

    int Download::getAudioCode() const {QMutexLocker locker(&this->mutex); return this->audio_code;}

    int Download::getVideoCode() const {QMutexLocker locker(&this->mutex); return this->video_code;}

    QString Download::getVideoFormat() const {QMutexLocker locker(&this->mutex); return this->video_format;}

    QString Download::getTitle() const {QMutexLocker locker(&this->mutex); return this->title;}

    QString Download::getSaveName() const {QMutexLocker locker(&this->mutex); return this->save_name;}

    QString Download::getFilePath() const {QMutexLocker locker(&this->mutex); return this->file_path;}

    QString Download::getSuffix() const {QMutexLocker locker(&this->mutex); return this->suffix;}

    int Download::getProgress() const {QMutexLocker locker(&this->mutex); return this->progress;}

    bool Download::getDownloadState() const {QMutexLocker locker(&this->mutex); return this->download_state;}

    bool Download::getMetadata() const {QMutexLocker locker(&this->mutex); return this->metadata;}

    bool Download::getSubtitles() const {QMutexLocker locker(&this->mutex); return this->subtitles;}

    bool Download::getAutoGeneratedSubtitles() const {QMutexLocker locker(&this->mutex); return this->auto_generated_subtitles;}

    void Download::setAudioCode(const int audioCode) {QMutexLocker locker(&this->mutex); this->audio_code = audioCode;}

    void Download::setVideoCode(const int videoCode) {QMutexLocker locker(&this->mutex); this->video_code = videoCode;}

    void Download::setVideoFormat(const QString& videoFormat) {QMutexLocker locker(&this->mutex); this->video_format = videoFormat;}

    void Download::setSaveName(const QString& saveName) {QMutexLocker locker(&this->mutex); this->save_name = saveName;}

    void Download::setFilePath(const QString& filePath) {QMutexLocker locker(&this->mutex); this->file_path = filePath;}

    void Download::setSuffix(const QString& suf) {QMutexLocker locker(&this->mutex); this->suffix = suf;}

    void Download::setProgress(const int prog) {QMutexLocker locker(&this->mutex); this->progress = prog;}

    void Download::setDownloadState(const bool downloadState) {QMutexLocker locker(&this->mutex); this->download_state = downloadState;}

    void Download::setMetadata(const bool met) {QMutexLocker locker(&this->mutex); this->metadata = met;}

    void Download::setSubtitles(const bool subt) {QMutexLocker locker(&this->mutex); this->subtitles = subt;}

    void Download::setAutoGeneratedSubtitles(const bool autoGeneratedSubtitles) {QMutexLocker locker(&this->mutex); this->auto_generated_subtitles = autoGeneratedSubtitles;}

    QJsonObject Download::toJson() const {
        QMutexLocker locker(&this->mutex);

        QJsonObject obj;

        obj[DB_CONSTANTS::JSON_FORMAT::USER_ID] = this->id;
        obj[DB_CONSTANTS::JSON_FORMAT::URL] = this->url;
        obj[DB_CONSTANTS::JSON_FORMAT::AUDIO_CODE] = this->audio_code;
        obj[DB_CONSTANTS::JSON_FORMAT::VIDEO_CODE] = this->video_code;
        obj[DB_CONSTANTS::JSON_FORMAT::VIDEO_FORMAT] = this->video_format;
        obj[DB_CONSTANTS::JSON_FORMAT::TITLE] = this->title;
        obj[DB_CONSTANTS::JSON_FORMAT::SAVE_NAME] = this->save_name;
        obj[DB_CONSTANTS::JSON_FORMAT::FILE_PATH] = this->file_path;
        obj[DB_CONSTANTS::JSON_FORMAT::SUFFIX] = this->suffix;
        obj[DB_CONSTANTS::JSON_FORMAT::PROGRESS] = this->progress;
        obj[DB_CONSTANTS::JSON_FORMAT::DOWNLOAD_STATE] = this->download_state;
        obj[DB_CONSTANTS::JSON_FORMAT::METADATA] = this->metadata;
        obj[DB_CONSTANTS::JSON_FORMAT::SUBTITLES] = this->subtitles;
        obj[DB_CONSTANTS::JSON_FORMAT::AUTO_GENERATED_SUBTITLES] = this->auto_generated_subtitles;

        return obj;
    }

    Download Download::fromJson(const QJsonObject& obj) {
        const auto id = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt();
        const auto url = obj[DB_CONSTANTS::JSON_FORMAT::URL].toString();
        const auto ac = obj[DB_CONSTANTS::JSON_FORMAT::AUDIO_CODE].toInt();
        const auto vc = obj[DB_CONSTANTS::JSON_FORMAT::VIDEO_CODE].toInt();
        const auto vf = obj[DB_CONSTANTS::JSON_FORMAT::VIDEO_FORMAT].toString();
        const auto tt = obj[DB_CONSTANTS::JSON_FORMAT::TITLE].toString();
        const auto sn = obj[DB_CONSTANTS::JSON_FORMAT::SAVE_NAME].toString();
        const auto fp = obj[DB_CONSTANTS::JSON_FORMAT::FILE_PATH].toString();
        const auto suf = obj[DB_CONSTANTS::JSON_FORMAT::SUFFIX].toString();
        const auto prog = obj[DB_CONSTANTS::JSON_FORMAT::PROGRESS].toInt();
        const auto ds = obj[DB_CONSTANTS::JSON_FORMAT::DOWNLOAD_STATE].toBool();
        const auto met = obj[DB_CONSTANTS::JSON_FORMAT::METADATA].toBool();
        const auto subt = obj[DB_CONSTANTS::JSON_FORMAT::SUBTITLES].toBool();
        const auto a_subt = obj[DB_CONSTANTS::JSON_FORMAT::AUTO_GENERATED_SUBTITLES].toBool();

        return {id, url, ac, vc, vf, tt, sn, fp, suf, prog, ds, met, subt, a_subt};
    }

    QJsonObject Download::toJsonList(const QList<Download>& list) {
        QJsonObject obj;
        QJsonArray arr;

        for (const auto& item : list) {arr.append(item.toJson());}
        obj[DB_CONSTANTS::JSON_FORMAT::PARAMETERS] = arr;

        return obj;
    }

    QList<Download> Download::fromJsonList(const QJsonObject& obj) {
        QList<Download> list;
        for (const auto arr = obj[DB_CONSTANTS::JSON_FORMAT::PARAMETERS].toArray(); const auto& item : arr) {list.append(fromJson(item.toObject()));}
        return list;
    }
}
