
#include "core/BasicTools.hpp"
#include "core/SharedStorage.hpp"
#include "ui/DownloadConfig.hpp"
#include "ui/NoticeView.hpp"
#include "ui/ShowItags.hpp"
#include <QFileDialog>
#include <QLineEdit>
#include <QPushButton>
#include <QTimer>

namespace UI {
    // Public

    //DownloadConfig::DownloadConfig(QWidget* parent) : QDialog(parent), idd(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_ID), id(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_ID), url(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_URL), title(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_TITLE), ifAudio(UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO), audioCode(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_AUDIO_CODE), videoCode(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_VIDEO_CODE), videoFormat(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_VIDEO_FORMAT), progress(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_PROGRESS), downloadState(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_DOWNLOAD_STATE), metadata(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_METADATA), subtitles(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_SUBTITLES), autoGeneratedSubtitles(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_AUTO_GENERATED_SUBTITLES), filePath(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_FILE_PATH), saveName(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_SAVE_NAME), suffix(CONTAINER_CONSTANTS::DOWNLOAD::DEFAULT_SUFFIX) {
    DownloadConfig::DownloadConfig(QWidget* parent) : QDialog(parent), idd(-1), id(-1), url(QString()), title(QString()), ifAudio(UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO), audioCode(0), videoCode(0), videoFormat(QString()), progress(0), downloadState(false), metadata(false), subtitles(false), autoGeneratedSubtitles(false), filePath(QString()), saveName(QString()), suffix(QString()) {
        // Timer
        this->timer1 = new QTimer(this);
        this->timer1->setInterval(UI_CONSTANTS::DOWNLOAD_CONFIG::WAIT_INTERVAL_FOR_URL_INPUTS);
        this->timer1->setSingleShot(true);

        this->timer2 = new QTimer(this);
        this->timer2->setInterval(UI_CONSTANTS::DOWNLOAD_CONFIG::WAIT_INTERVAL_FOR_URL_INPUTS);
        this->timer2->setSingleShot(true);

        this->timer3 = new QTimer(this);
        this->timer3->setInterval(UI_CONSTANTS::DOWNLOAD_CONFIG::WAIT_INTERVAL_FOR_URL_INPUTS);
        this->timer3->setSingleShot(true);

        this->timer4 = new QTimer(this);
        this->timer4->setInterval(UI_CONSTANTS::DOWNLOAD_CONFIG::WAIT_INTERVAL_FOR_URL_INPUTS);
        this->timer4->setSingleShot(true);

        // Main
        this->mainLayout = new QVBoxLayout;

        // General Information
        this->basicBox = new QGroupBox(UI_CONSTANTS::DOWNLOAD_CONFIG::GENERAL_INFORMATION());
        this->basicForm = new QFormLayout;

        this->urlLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::LINK(), this);
        this->urlLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->urlEdit = new QLineEdit(this);
        this->urlEdit->setPlaceholderText(UI_CONSTANTS::DOWNLOAD_CONFIG::HINT_TEXT_URL_EDIT());
        this->urlEdit->setFixedSize(UI_CONSTANTS::DOWNLOAD_CONFIG::LINEEDIT_SIZE.first, UI_CONSTANTS::DOWNLOAD_CONFIG::LINEEDIT_SIZE.second);

        this->titleLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::TITLE(), this);
        this->titleLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->titleEdit = new QLineEdit(this);
        this->titleEdit->setEnabled(false);
        this->titleEdit->setFixedSize(UI_CONSTANTS::DOWNLOAD_CONFIG::LINEEDIT_SIZE.first, UI_CONSTANTS::DOWNLOAD_CONFIG::LINEEDIT_SIZE.second);

        this->basicForm->addRow(this->urlLab, this->urlEdit);
        this->basicForm->addRow(this->titleLab, this->titleEdit);
        this->basicForm->setFormAlignment(Qt::AlignHCenter | Qt::AlignTop);
        this->basicForm->setFieldGrowthPolicy(QFormLayout::FieldsStayAtSizeHint);

        this->basicBox->setLayout(this->basicForm);
        this->mainLayout->addWidget(this->basicBox);

        // Download Mode
        this->modeBox = new QGroupBox(UI_CONSTANTS::DOWNLOAD_CONFIG::DOWNLOAD_CONFIG());
        this->modeForm = new QFormLayout;
        this->modeLayout = new QHBoxLayout;

        this->modeLabel = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::MODE(), this);
        this->modeLabel->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->modeCombo = new QComboBox(this);
        this->modeCombo->setFixedWidth(UI_CONSTANTS::DOWNLOAD_CONFIG::COMBO_SIZE.first);
        this->modeCombo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::BEST_AUDIO());
        this->modeCombo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::BEST_VIDEO());
        this->modeCombo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::PERSONALIZED());

        this->showITagsBtn = new QPushButton(UI_CONSTANTS::DOWNLOAD_CONFIG::SHOW_I_TAGS(), this);
        this->showITagsBtn->setVisible(false);

        this->modeLayout->addStretch();
        this->modeLayout->addWidget(this->modeCombo);
        this->modeLayout->addWidget(this->showITagsBtn);
        this->modeLayout->addStretch();

        this->audioLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::AUDIO_I_TAG(), this);
        this->audioLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->audioEdit = new QLineEdit(this);
        this->audioEdit->setFixedWidth(UI_CONSTANTS::DOWNLOAD_CONFIG::COMBO_SIZE.first);
        this->audioEdit->setPlaceholderText(UI_CONSTANTS::DOWNLOAD_CONFIG::EXAMPLE_AUDIO_I_TAG());

        this->videoLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::VIDEO_I_TAG(), this);
        this->videoLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->videoEdit = new QLineEdit(this);
        this->videoEdit->setFixedWidth(UI_CONSTANTS::DOWNLOAD_CONFIG::COMBO_SIZE.first);
        this->videoEdit->setPlaceholderText(UI_CONSTANTS::DOWNLOAD_CONFIG::EXAMPLE_VIDEO_I_TAG());

        this->nonStandardVideoLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::NON_STANDARD_VIDEO_I_TAG(), this);
        this->nonStandardVideoLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->nonStandardVideoLab->setToolTip(UI_CONSTANTS::DOWNLOAD_CONFIG::AI_UPSCALED_ONLY());
        this->nonStandardVideoEdit = new QLineEdit(this);
        this->nonStandardVideoEdit->setFixedWidth(UI_CONSTANTS::DOWNLOAD_CONFIG::COMBO_SIZE.first);
        this->nonStandardVideoEdit->setPlaceholderText(UI_CONSTANTS::DOWNLOAD_CONFIG::EXAMPLE_NON_STANDARD_VIDEO_I_TAG());

        this->modeForm->addRow(this->modeLabel, this->modeLayout);
        this->modeForm->addRow(this->audioLab, this->audioEdit);
        this->modeForm->addRow(this->videoLab, this->videoEdit);
        this->modeForm->addRow(this->nonStandardVideoLab, this->nonStandardVideoEdit);

        this->audioLab->setVisible(false);
        this->audioEdit->setVisible(false);
        this->videoLab->setVisible(false);
        this->videoEdit->setVisible(false);
        this->nonStandardVideoLab->setVisible(false);
        this->nonStandardVideoEdit->setVisible(false);

        this->metLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::METADATA_LAB(), this);
        this->metLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->metCombo = new QComboBox(this);
        this->metCombo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::WITHOUT_METADATA());
        this->metCombo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_METADATA());
        this->metCombo->setFixedWidth(UI_CONSTANTS::DOWNLOAD_CONFIG::COMBO_SIZE.first);

        this->subtLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::SUBTITLE_LAB(), this);
        this->subtLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->subtCombo = new QComboBox(this);
        this->subtCombo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::WITHOUT_SUBTITLES());
        //this->subtCombo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_SUBTITLES());
        this->subtCombo->setFixedWidth(UI_CONSTANTS::DOWNLOAD_CONFIG::COMBO_SIZE.first);

        this->at_subt_lab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::AUTO_GENERATED_SUBTITLES_LAB(), this);
        this->at_subt_lab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->at_subt_combo = new QComboBox(this);
        this->at_subt_combo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::WITHOUT_AUTO_GENERATED_SUBTITLES());
        //this->at_subt_combo->addItem(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_AUTO_GENERATED_SUBTITLES());
        this->at_subt_combo->setFixedWidth(UI_CONSTANTS::DOWNLOAD_CONFIG::COMBO_SIZE.first);

        this->modeForm->addRow(this->metLab, this->metCombo);
        this->modeForm->addRow(this->subtLab, this->subtCombo);
        this->modeForm->addRow(this->at_subt_lab, this->at_subt_combo);
        this->modeForm->setFormAlignment(Qt::AlignHCenter | Qt::AlignTop);
        this->modeForm->setFieldGrowthPolicy(QFormLayout::FieldsStayAtSizeHint);

        this->modeBox->setLayout(this->modeForm);
        this->mainLayout->addWidget(this->modeBox);

        // Output
        this->outputBox = new QGroupBox(UI_CONSTANTS::DOWNLOAD_CONFIG::OUTPUT());
        this->outputForm = new QFormLayout;
        this->outputLayout = new QHBoxLayout;

        this->outputLab = new QLabel(UI_CONSTANTS::DOWNLOAD_CONFIG::SAVE_PATH_LAB(), this);
        this->outputLab->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
        this->outputEdit = new QLineEdit(this);
        this->outputEdit->setEnabled(false);
        this->outputEdit->setFixedSize(UI_CONSTANTS::DOWNLOAD_CONFIG::OUTPUT_LAYOUT_LINEEDIT_SIZE.first, UI_CONSTANTS::DOWNLOAD_CONFIG::OUTPUT_LAYOUT_LINEEDIT_SIZE.second);
        this->outputBtn = new QPushButton(UI_CONSTANTS::DOWNLOAD_CONFIG::SAVE_AS(), this);

        this->outputLayout->addStretch();
        this->outputLayout->addWidget(this->outputLab);
        this->outputLayout->addWidget(this->outputEdit);
        this->outputLayout->addWidget(this->outputBtn);
        this->outputLayout->addStretch();
        this->outputLayout->setSpacing(UI_CONSTANTS::DOWNLOAD_CONFIG::DEFAULT_SPACING_LAYOUT);

        this->outputForm->addItem(this->outputLayout);
        this->outputBox->setLayout(this->outputForm);
        this->mainLayout->addWidget(this->outputBox);

        // Save
        this->buttonLayout = new QHBoxLayout;

        this->okBtn = new QPushButton(UI_CONSTANTS::DOWNLOAD_CONFIG::CONFIRM(), this);
        this->okBtn->setEnabled(false);

        this->buttonLayout->addStretch();
        this->buttonLayout->addWidget(this->okBtn);
        this->buttonLayout->addStretch();

        this->mainLayout->addLayout(this->buttonLayout);

        // More Settings
        this->setLayout(this->mainLayout);
        this->setWindowIcon(QIcon(UI_CONSTANTS::NOTICE_VIEW::RESOURCES_PATH() + QDir::separator() + UI_CONSTANTS::NOTICE_VIEW::ICON_NAME));
        this->setWindowTitle(UI_CONSTANTS::DOWNLOAD_CONFIG::GENERAL_CONFIG());
        this->setFixedSize(UI_CONSTANTS::DOWNLOAD_CONFIG::WINDOW_SIZE.first, UI_CONSTANTS::DOWNLOAD_CONFIG::WINDOW_SIZE.second);
        this->setStyleSheet(UI_CONSTANTS::DOWNLOAD_CONFIG::STYLE);

        connect(this->urlEdit, &QLineEdit::textChanged, this, [this](const QString&){this->timer1->start();});
        connect(this->timer1, &QTimer::timeout, this, [this](){this->timer1Finished(this->urlEdit->text());});
        connect(this->showITagsBtn, &QPushButton::clicked, this, &DownloadConfig::showItagsBtnClicked);
        connect(this->audioEdit, &QLineEdit::textChanged, this, [this](const QString&){this->timer2->start();});
        connect(this->timer2, &QTimer::timeout, this, [this](){this->timer2Finished(this->audioEdit->text());});
        connect(this->videoEdit, &QLineEdit::textChanged, this, [this](const QString&){this->timer3->start();});
        connect(this->timer3, &QTimer::timeout, this, [this](){this->timer3Finished(this->videoEdit->text());});
        connect(this->nonStandardVideoEdit, &QLineEdit::textChanged, this, [this](const QString&){this->timer4->start();});
        connect(this->timer4, &QTimer::timeout, this, [this](){this->timer4Finished(this->nonStandardVideoEdit->text());});
        connect(this->modeCombo, &QComboBox::currentIndexChanged, this, &DownloadConfig::modeComboChanged);
        connect(this->metCombo, &QComboBox::currentIndexChanged, this, &DownloadConfig::metComboChanged);
        //connect(this->subtCombo, &QComboBox::currentIndexChanged, this, &DownloadConfig::subtComboChanged);
        //connect(this->at_subt_combo, &QComboBox::currentIndexChanged, this, &DownloadConfig::atSubtComboChanged);
        connect(this->outputBtn, &QPushButton::clicked, this, &DownloadConfig::outputBtnClicked);
        connect(this->okBtn, &QPushButton::clicked, this, &DownloadConfig::okBtnClicked);
    }

    int DownloadConfig::getId() const {return this->normalMode ? this->id : this->idd;}

    void DownloadConfig::requestEdit(const CONTAINER::Download& download) {
        this->normalMode = false;
        this->askForSavePath = false;

        this->idd = download.getId();
        this->url = download.getUrl();
        this->audioCode = download.getAudioCode();
        this->videoCode = download.getVideoCode();
        this->videoFormat = download.getVideoFormat();
        this->title = download.getTitle();
        this->filePath = download.getFilePath();
        this->saveName = download.getSaveName();
        this->suffix = download.getSuffix();
        this->progress = download.getProgress();
        this->downloadState = download.getDownloadState();
        this->metadata = download.getMetadata();
        //this->subtitles = download.getSubtitles();
        //this->autoGeneratedSubtitles = download.getAutoGeneratedSubtitles();

        this->urlEdit->setText(this->url);
        this->urlEdit->setEnabled(false);
        this->audioEdit->setText(this->audioCode == 0 ? QString() : QString::number(this->audioCode));
        this->videoEdit->setText(this->videoCode == 0 ? QString() : QString::number(this->videoCode));
        this->nonStandardVideoEdit->setText(this->videoFormat.trimmed().isEmpty() ? QString() : this->videoFormat.trimmed());
        this->titleEdit->setText(this->title);
        this->metCombo->setCurrentText(this->metadata ? UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_METADATA() : UI_CONSTANTS::DOWNLOAD_CONFIG::WITHOUT_METADATA());
        //this->subtCombo->setCurrentText(this->subtitles ? UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_SUBTITLES() : UI_CONSTANTS::DOWNLOAD_CONFIG::WITHOUT_SUBTITLES());
        //this->at_subt_combo->setCurrentText(this->autoGeneratedSubtitles ? UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_AUTO_GENERATED_SUBTITLES() : UI_CONSTANTS::DOWNLOAD_CONFIG::WITHOUT_AUTO_GENERATED_SUBTITLES());
        this->outputEdit->setText(this->filePath + QDir::separator() + this->saveName + UI_CONSTANTS::MAIN_WINDOW::POINT + this->suffix);

        if (this->audioCode == 0 && this->videoCode == 0) {
            if (CORE_CONSTANTS::MEDIA_FILTERS::AUDIO_FILTERS::SUPPORTED_AUDIO_FORMATS.contains(this->suffix)) this->modeCombo->setCurrentText(UI_CONSTANTS::DOWNLOAD_CONFIG::BEST_AUDIO());

            else this->modeCombo->setCurrentText(UI_CONSTANTS::DOWNLOAD_CONFIG::BEST_VIDEO());
        }

        else this->modeCombo->setCurrentText(UI_CONSTANTS::DOWNLOAD_CONFIG::PERSONALIZED());
    }


    // Private Slots

    void DownloadConfig::timer1Finished(const QString& text) {
        if (this->normalMode) {
            if (const auto text_t = text.trimmed(); !text_t.isEmpty()) {
                if (CORE::MEDIA_INFO::ifValidURL(text_t)) {
                    this->url = CORE::MEDIA_INFO::cutURL(text_t);

                    const auto tools = CORE::SharedStorage::instance().getToolsPath();

                    this->showITagsBtn->setEnabled(false);
                    this->urlEdit->setEnabled(false);
                    this->modeCombo->setEnabled(false);
                    this->metCombo->setEnabled(false);
                    //this->subtCombo->setEnabled(false);
                    //this->at_subt_combo->setEnabled(false);
                    this->audioEdit->setEnabled(false);
                    this->videoEdit->setEnabled(false);
                    this->nonStandardVideoEdit->setEnabled(false);
                    this->outputBtn->setEnabled(false);

                    sleepForMilliseconds(UI_CONSTANTS::DOWNLOAD_CONFIG::SLEEP_TIME);

                    try {
                        if (const auto tt = CORE::MEDIA_INFO::getTitleFromURL(tools->getYtDlpPath(), tools->getFFmpegPath(), this->url); !tt.isEmpty()) {
                            this->titleEdit->setText(tt);
                            this->title = tt;
                        }

                        else {
                            this->titleEdit->setText(UI_CONSTANTS::DOWNLOAD_CONFIG::TITLE_FAILED());
                            this->title = UI_CONSTANTS::DOWNLOAD_CONFIG::TITLE_FAILED();
                        }

                    }

                    catch (...) {
                        this->titleEdit->setText(UI_CONSTANTS::DOWNLOAD_CONFIG::TITLE_FAILED());
                        this->title = UI_CONSTANTS::DOWNLOAD_CONFIG::TITLE_FAILED();
                    }

                    this->showITagsBtn->setEnabled(true);
                    this->urlEdit->setEnabled(true);
                    this->modeCombo->setEnabled(true);
                    this->metCombo->setEnabled(true);
                    //this->subtCombo->setEnabled(true);
                    //this->at_subt_combo->setEnabled(true);
                    this->audioEdit->setEnabled(true);
                    this->videoEdit->setEnabled(true);
                    this->nonStandardVideoEdit->setEnabled(true);
                    this->outputBtn->setEnabled(true);
                }

                else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_URL(text_t));
            }

            else {
                this->url = QString();
                this->title = QString();
                this->titleEdit->setText(QString());
            }
        }
    }

    void DownloadConfig::timer2Finished(const QString& audio_code) {
        if (const auto act = audio_code.trimmed(); !act.isEmpty()) {
            if (const auto ac = act.toInt(); CORE::MEDIA_INFO::ifValidAudioCode(ac)) this->audioCode = ac;

            else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_AUDIO_I_TAG(act));
        }

        else this->audioCode = 0;
    }

    void DownloadConfig::timer3Finished(const QString& video_code) {
        if (const auto vct = video_code.trimmed(); !vct.isEmpty()) {
            if (const auto vc = vct.toInt(); CORE::MEDIA_INFO::ifValidVideoCode(vc)) this->videoCode = vc;

            else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_VIDEO_I_TAG(vct));
        }

        else this->videoCode = 0;
    }

    void DownloadConfig::timer4Finished(const QString& video_format) {
        if (const auto vf = video_format.trimmed(); !vf.isEmpty()) {
            if (CORE::MEDIA_INFO::ifValidVideoFormat(vf)) this->videoFormat = vf;

            else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_NON_STANDARD_VIDEO_I_TAG(vf));
        }

        else this->videoFormat = QString();
    }

    void DownloadConfig::showItagsBtnClicked() const {
        if (const auto tt = this->titleEdit->text().trimmed(); tt.isEmpty() || tt.compare(UI_CONSTANTS::DOWNLOAD_CONFIG::TITLE_FAILED(), Qt::CaseInsensitive) == 0) NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_URL(this->urlEdit->text().trimmed()));

        else {
            auto* show = new ShowItags(this->url);
            show->setAttribute(Qt::WA_DeleteOnClose);
            show->exec();
        }
    }

    void DownloadConfig::modeComboChanged() {
        if (this->modeCombo->currentText().compare(UI_CONSTANTS::DOWNLOAD_CONFIG::PERSONALIZED(), Qt::CaseInsensitive) == 0) {
            this->showITagsBtn->setVisible(true);
            this->audioLab->setVisible(true);
            this->audioEdit->setVisible(true);
            this->videoLab->setVisible(true);
            this->videoEdit->setVisible(true);
            this->nonStandardVideoLab->setVisible(true);
            this->nonStandardVideoEdit->setVisible(true);
        }

        else {
            this->showITagsBtn->setVisible(false);
            this->audioLab->setVisible(false);
            this->audioEdit->setVisible(false);
            this->videoLab->setVisible(false);
            this->videoEdit->setVisible(false);
            this->nonStandardVideoLab->setVisible(false);
            this->nonStandardVideoEdit->setVisible(false);
            this->audioCode = 0;
            this->videoCode = 0;
        }
    }

    void DownloadConfig::metComboChanged() {this->metadata = this->metCombo->currentText().compare(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_METADATA(), Qt::CaseInsensitive) == 0;}

    //void DownloadConfig::subtComboChanged() {this->subtitles = this->subtCombo->currentText().compare(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_SUBTITLES(), Qt::CaseInsensitive) == 0;}

    //void DownloadConfig::atSubtComboChanged() {this->autoGeneratedSubtitles = this->at_subt_combo->currentText().compare(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_AUTO_GENERATED_SUBTITLES(), Qt::CaseInsensitive) == 0;}

    void DownloadConfig::outputBtnClicked() {
        if (CORE::MEDIA_INFO::ifValidURL(this->url) && this->title.compare(UI_CONSTANTS::DOWNLOAD_CONFIG::TITLE_FAILED(), Qt::CaseInsensitive) != 0) {
            if (const auto m = this->modeCombo->currentText(); m.compare(UI_CONSTANTS::DOWNLOAD_CONFIG::BEST_AUDIO(), Qt::CaseInsensitive) == 0) {
                this->ifAudio = UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO;
                this->audioCode = 0;
                this->videoCode = 0;
                this->videoFormat = QString();
            }

            else if (m.compare(UI_CONSTANTS::DOWNLOAD_CONFIG::BEST_VIDEO(), Qt::CaseInsensitive) == 0) {
                this->ifAudio = !UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO;
                this->audioCode = 0;
                this->videoCode = 0;
                this->videoFormat = QString();
            }

            else if (m.compare(UI_CONSTANTS::DOWNLOAD_CONFIG::PERSONALIZED(), Qt::CaseInsensitive) == 0) {
                this->timer3Finished(this->videoEdit->text().trimmed());

                if (CORE::MEDIA_INFO::ifValidAudioCode(this->audioCode)) {
                    const auto f1 = CORE::MEDIA_INFO::ifValidVideoCode(this->videoCode);
                    const auto f2 = CORE::MEDIA_INFO::ifValidVideoFormat(this->videoFormat.trimmed());

                    if (f1 && !this->videoFormat.isEmpty() && f2) {
                        if (NoticeView::confirmation(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::CHOOSE_BETWEEN_VI_AND_VI_AI())) {
                            this->ifAudio = !UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO;
                            this->videoCode = 0;
                        }

                        else return;
                    }

                    else if (f1) {
                        this->ifAudio = !UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO;
                        this->videoFormat = QString();
                    }

                    else if (!this->videoFormat.isEmpty() && f2) {
                        this->ifAudio = !UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO;
                        this->videoCode = 0;
                    }

                    else {
                        this->ifAudio = UI_CONSTANTS::SETTINGS_VIEW::DEFAULT_IF_AUDIO;
                        this->videoCode = 0;
                        this->videoFormat = QString();
                    }
                }

                else {
                    NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::REQUIRED_AUDIO_I_TAG());
                    return;
                }
            }

            this->metadata = this->metCombo->currentText().compare(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_METADATA(), Qt::CaseInsensitive) == 0;
            //this->subtitles = this->subtCombo->currentText().compare(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_SUBTITLES(), Qt::CaseInsensitive) == 0;
            this->subtitles = false;
            //this->autoGeneratedSubtitles = this->at_subt_combo->currentText().compare(UI_CONSTANTS::DOWNLOAD_CONFIG::WITH_AUTO_GENERATED_SUBTITLES(), Qt::CaseInsensitive) == 0;
            this->autoGeneratedSubtitles = false;

            if (this->askForSavePath) {if (!NoticeView::confirmation(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::ASK_FOR_SAVE_PATH())) return; this->askForSavePath = false;}

            this->urlEdit->setEnabled(false);
            this->modeCombo->setEnabled(false);
            this->showITagsBtn->setEnabled(false);
            this->audioEdit->setEnabled(false);
            this->videoEdit->setEnabled(false);
            this->nonStandardVideoEdit->setEnabled(false);
            this->metCombo->setEnabled(false);
            //this->subtCombo->setEnabled(false);
            //this->at_subt_combo->setEnabled(false);

            QFileDialog dialog {
                this,
                UI_CONSTANTS::DOWNLOAD_CONFIG::SAVE_AS(),
                QStandardPaths::writableLocation(QStandardPaths::DownloadLocation) + QDir::separator() + this->title,
                this->ifAudio ? CORE_CONSTANTS::MEDIA_FILTERS::AUDIO_FILTERS::FILTER_AUDIO : CORE_CONSTANTS::MEDIA_FILTERS::VIDEO_FILTERS::FILTER_VIDEO,
            };

            #ifdef Q_OS_MAC
                dialog.setOptions(QFileDialog::DontUseNativeDialog);
            #elif defined(Q_OS_WIN)
            #elif defined(Q_OS_LINUX)
                dialog.setFileMode(QFileDialog::AnyFile);
                dialog.setOption(QFileDialog::ShowDirsOnly, false);
                dialog.setAcceptMode(QFileDialog::AcceptSave);
            #endif

            dialog.setFilter(dialog.filter() | QDir::Hidden | QDir::NoDotAndDotDot);

            if (dialog.exec() == Accepted) {
                if (const auto fullPath = dialog.selectedFiles().first(); !fullPath.isEmpty()) {
                    const auto folder = QFileInfo(fullPath).absolutePath();
                    const auto fileName = QFileInfo(fullPath).completeBaseName();
                    const auto selectedFilter = dialog.selectedNameFilter();
                    const auto suf = this->ifAudio ? CORE_CONSTANTS::MEDIA_FILTERS::AUDIO_FILTERS::EXTRACT_AUDIO_FILTER(selectedFilter) : CORE_CONSTANTS::MEDIA_FILTERS::VIDEO_FILTERS::EXTRACT_VIDEO_FILTER(selectedFilter);

                    if (CORE::MEDIA_INFO::ifValidPath(folder)) {
                        if (CORE::MEDIA_INFO::ifValidSaveName(fileName)) {
                            if (CORE::MEDIA_INFO::ifValidSuffix(suf)) {
                                this->okBtn->setEnabled(true);
                                this->filePath = folder;
                                this->saveName = fileName;
                                this->suffix = suf;
                                this->outputEdit->setText(this->filePath + QDir::separator() + this->saveName + UI_CONSTANTS::MAIN_WINDOW::POINT + this->suffix);
                            }

                            else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_SUFFIX(suf));
                        }

                        else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_SAVE_NAME(fileName));
                    }

                    else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::INVALID_FILE_PATH(folder));
                }

                else {
                    this->outputEdit->setText(QString());
                    this->filePath = QString();
                    this->saveName = QString();
                    this->suffix = QString();
                }
            }
        }

        else NoticeView::warning(UI_CONSTANTS::DOWNLOAD_CONFIG::WARNING(), UI_CONSTANTS::DOWNLOAD_CONFIG::REQUIRED_URL());
    }

    void DownloadConfig::okBtnClicked() {
        this->id = nextId++;
        //CORE::SharedStorage::instance().addDownload({(this->normalMode ? this->id : this->idd), this->url, this->audioCode, this->videoCode, this->videoFormat, this->title, this->saveName, this->filePath, this->suffix, (this->normalMode ? 0 : this->progress), (this->normalMode ? false : this->downloadState),  this->metadata, this->subtitles, this->autoGeneratedSubtitles});
        CORE::SharedStorage::instance().addDownload({(this->normalMode ? this->id : this->idd), this->url, this->audioCode, this->videoCode, this->videoFormat, this->title, this->saveName, this->filePath, this->suffix, (this->normalMode ? 0 : this->progress), (this->normalMode ? false : this->downloadState),  this->metadata, false, false});
        accept();
    }


    // Private

    void DownloadConfig::sleepForMilliseconds(const int milliseconds) {
        QEventLoop loop;
        QTimer::singleShot(milliseconds, &loop, &QEventLoop::quit);
        loop.exec();
    }
}
