
#include "constants/Db_Constants.hpp"
#include "db/DataBase.hpp"
#include <QDir>
#include <QStandardPaths>

namespace DB {
    // Protected

    DataBase::DataBase(QObject* parent) : QObject(parent) {}

    bool DataBase::init() {
        this->dataBaseDir = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);

        if (const QDir dir; !dir.exists(this->dataBaseDir)) dir.mkpath(this->dataBaseDir);

        this->dataBaseDir = this->dataBaseDir + QDir::separator() + DB_CONSTANTS::DB_MANAGER::DATABASE_NAME;

        if (!QFile::exists(this->dataBaseDir)) {
            QFile file(this->dataBaseDir);

            if (!file.open(QIODevice::WriteOnly)) return false;

            file.close();

            QFile::setPermissions(this->dataBaseDir,
                QFileDevice::ReadOwner | QFileDevice::WriteOwner |
                QFileDevice::ReadUser | QFileDevice::WriteUser);
        }

        this->db = QSqlDatabase::addDatabase(DB_CONSTANTS::DB_MANAGER::CONNECTION_TYPE);
        this->db.setDatabaseName(this->dataBaseDir);

        return this->db.open() && this->createTable();
    }

    bool DataBase::isOpen() const {return this->db.isOpen();}

    bool DataBase::isEmpty() const {
        QSqlQuery q(this->db);

        q.prepare("SELECT 1 FROM downloads LIMIT 1");
        q.exec();

        return !q.next();
    }

    QString DataBase::getPath() const {return this->dataBaseDir;}

    bool DataBase::ifExists(const int id) const {
        QSqlQuery q(this->db);

        q.prepare("SELECT COUNT(*) FROM downloads WHERE id = :id");
        q.bindValue(":id", id);
        q.exec();

        return q.next() && q.value(0).toInt() > 0;
    }

    bool DataBase::add(const CONTAINER::Download& d) const {
        QSqlQuery q(this->db);

        q.prepare("INSERT INTO downloads (id, url, audio_code, video_code, video_format, title, save_name, file_path, suffix, progress, download_state, metadata, subtitles, auto_generated_subtitles)"
                  "VALUES (:id, :url, :ac, :vc, :vf, :tt, :sn, :fp, :suf, :prog, :ds, :met, :subt, :at_subt)");

        q.bindValue(":id", d.getId());
        q.bindValue(":url", d.getUrl());
        q.bindValue(":ac", d.getAudioCode());
        q.bindValue(":vc", d.getVideoCode());
        q.bindValue(":vf", d.getVideoFormat());
        q.bindValue(":tt", d.getTitle());
        q.bindValue(":sn", d.getSaveName());
        q.bindValue(":fp", d.getFilePath());
        q.bindValue(":suf", d.getSuffix());
        q.bindValue(":prog", 0);
        q.bindValue(":ds", 0);
        q.bindValue(":met", d.getMetadata() ? 1 : 0);
        q.bindValue(":subt", d.getSubtitles() ? 1 : 0);
        q.bindValue(":at_subt", d.getAutoGeneratedSubtitles() ? 1 : 0);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::remove(const int id) const {
        QSqlQuery q(this->db);

        q.prepare("DELETE FROM downloads WHERE id = :id");

        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::removeAll() const {
        QSqlQuery q(this->db);

        q.prepare("DELETE FROM downloads");

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateAudioCode(const int id, const int audioCode) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET audio_code = :ac WHERE id = :id");

        q.bindValue(":ac", audioCode);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateVideoCode(const int id, const int videoCode) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET video_code = :vc WHERE id = :id");

        q.bindValue(":vc", videoCode);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateVideoFormat(const int id, const QString& videoFormat) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET video_format = :vf WHERE id = :id");

        q.bindValue(":vf", videoFormat);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateSaveName(const int id, const QString& saveName) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET save_name = :sn WHERE id = :id");

        q.bindValue(":sn", saveName);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateFilePath(const int id, const QString& filePath) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET file_path = :fp WHERE id = :id");

        q.bindValue(":fp", filePath);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateSuffix(const int id, const QString& suffix) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET suffix = :suf WHERE id = :id");

        q.bindValue(":suf", suffix);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateProgress(const int id, const int progress) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET progress = :prog WHERE id = :id");

        q.bindValue(":prog", progress);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateDownloadState(const int id, const bool download_state) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET download_state = :d WHERE id = :id");

        q.bindValue(":d", download_state ? 1 : 0);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateMetadata(const int id, const bool metadata) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET metadata = :met WHERE id = :id");

        q.bindValue(":met", metadata ? 1 : 0);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateSubtitles(const int id, const bool subtitles) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET subtitles = :subt WHERE id = :id");

        q.bindValue(":subt", subtitles ? 1 : 0);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    bool DataBase::updateAutoGeneratedSubtitles(const int id, const bool autoGeneratedSubtitles) const {
        QSqlQuery q(this->db);

        q.prepare("UPDATE downloads SET auto_generated_subtitles = :at_subt WHERE id = :id");

        q.bindValue(":at_subt", autoGeneratedSubtitles ? 1 : 0);
        q.bindValue(":id", id);

        if (!q.exec()) return false;

        return q.numRowsAffected() > 0;
    }

    CONTAINER::Download DataBase::read(const int id) const {
        QSqlQuery q(this->db);

        q.prepare("SELECT id, url, audio_code, video_code, video_format, title, save_name, file_path, suffix, progress, download_state, metadata, subtitles, auto_generated_subtitles FROM downloads WHERE id = :id");
        q.bindValue(":id", id);

        if (!q.exec()) return {};

        if (q.next()) {
            const auto idd = q.value("id").toInt();
            const auto url = q.value("url").toString();
            const auto ac = q.value("audio_code").toInt();
            const auto vc = q.value("video_code").toInt();
            const auto vf = q.value("video_format").toString();
            const auto tt = q.value("title").toString();
            const auto sn = q.value("save_name").toString();
            const auto fp = q.value("file_path").toString();
            const auto suf = q.value("suffix").toString();
            const auto prog = q.value("progress").toInt();
            const auto ds = q.value("download_state").toBool();
            const auto met = q.value("metadata").toBool();
            const auto subt = q.value("subtitles").toBool();
            const auto a_subt = q.value("auto_generated_subtitles").toBool();

            return {idd, url, ac, vc, vf, tt, sn, fp, suf, prog, ds, met, subt, a_subt};
        }

        return {};
    }

    QList<CONTAINER::Download> DataBase::readAll() const {
        QList<CONTAINER::Download> list;

        QSqlQuery q(this->db);

        q.prepare("SELECT id, url, audio_code, video_code, video_format, title, save_name, file_path, suffix, progress, download_state, metadata, subtitles, auto_generated_subtitles FROM downloads");

        if (!q.exec()) return {};

        while (q.next()) {
            const auto idd = q.value("id").toInt();
            const auto url = q.value("url").toString();
            const auto ac = q.value("audio_code").toInt();
            const auto vc = q.value("video_code").toInt();
            const auto vf = q.value("video_format").toString();
            const auto tt = q.value("title").toString();
            const auto sn = q.value("save_name").toString();
            const auto fp = q.value("file_path").toString();
            const auto suf = q.value("suffix").toString();
            const auto prog = q.value("progress").toInt();
            const auto ds = q.value("download_state").toBool();
            const auto met = q.value("metadata").toBool();
            const auto subt = q.value("subtitles").toBool();
            const auto a_subt = q.value("auto_generated_subtitles").toBool();

            list.append({idd, url, ac, vc, vf, tt, sn, fp, suf, prog, ds, met, subt, a_subt});
        }

        return list;
    }


    // Private

    bool DataBase::createTable() const {
        QSqlQuery q(this->db);
        return q.exec(DB_CONSTANTS::DB_MANAGER::CREATE_TABLE);
    }
}
