
#include "core/BasicTools.hpp"
#include "db/DbManager.hpp"

namespace DB {
    // Public

    DbManager::DbManager(QObject *parent) : DataBase(parent) {(void)init();}

    QJsonObject DbManager::isOpenDB() const {
        QJsonObject obj;
        obj[DB_CONSTANTS::JSON_FORMAT::STATUS] = isOpen() ? DB_CONSTANTS::JSON_FORMAT::STATUS_OK : DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
        return obj;
    }

    QJsonObject DbManager::addDownload(const QJsonObject& obj) const {
        QJsonObject res;
        QJsonObject err;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            err[DB_CONSTANTS::JSON_FORMAT::USER_ID] = DB_CONSTANTS::JSON_FORMAT::ID_EXISTS();
        }

        else {
            const auto download = CONTAINER::Download::fromJson(obj);

            const auto url = download.getUrl();
            const auto audio_code = download.getAudioCode();
            const auto video_code = download.getVideoCode();
            const auto video_format = download.getVideoFormat();
            const auto title = download.getTitle();
            const auto save_name = download.getSaveName();
            const auto file_path = download.getFilePath();
            const auto suffix = download.getSuffix();
            const auto metadata = download.getMetadata();
            const auto subtitles = download.getSubtitles();
            const auto auto_generated_subtitles = download.getAutoGeneratedSubtitles();

            bool flag = true;
            const auto f_id = CORE::MEDIA_INFO::ifValidId(userId);
            const auto f_ac = CORE::MEDIA_INFO::ifValidAudioCode(audio_code);
            const auto f_vc = CORE::MEDIA_INFO::ifValidVideoCode(video_code);
            const auto f_vf = CORE::MEDIA_INFO::ifValidVideoFormat(video_format);
            const auto f_t = CORE::MEDIA_INFO::ifValidTitle(title);
            const auto f_sn = CORE::MEDIA_INFO::ifValidSaveName(save_name);
            const auto f_fp = CORE::MEDIA_INFO::ifValidPath(file_path);
            const auto f_s = CORE::MEDIA_INFO::ifValidSuffix(suffix);

            if (!f_id) {
                flag = false;
                err[DB_CONSTANTS::JSON_FORMAT::USER_ID] = DB_CONSTANTS::JSON_FORMAT::ERROR_ID();
            }

            if (audio_code != 0 && !f_ac) {
                flag = false;
                err[DB_CONSTANTS::JSON_FORMAT::AUDIO_CODE] = CORE_CONSTANTS::MEDIA_I_TAGS::AUDIO_I_TAGS::ERROR_MESSAGE_I_TAG();
            }

            if (video_code != 0 && !video_format.isEmpty() && CORE_CONSTANTS::BASIC_TOOLS::PATTERN_VIDEO_FORMAT.match(video_format).hasMatch() && !f_vc) {
                flag = false;
                err[DB_CONSTANTS::JSON_FORMAT::VIDEO_CODE] = CORE_CONSTANTS::MEDIA_I_TAGS::VIDEO_I_TAGS::ERROR_MESSAGE_I_TAG();
            }

            if (!f_vf) err[DB_CONSTANTS::JSON_FORMAT::VIDEO_FORMAT] = CORE_CONSTANTS::MEDIA_I_TAGS::VIDEO_I_TAGS::ERROR_MESSAGE_FORMAT();

            if (!f_t) {
                flag = false;
                err[DB_CONSTANTS::JSON_FORMAT::TITLE] = DB_CONSTANTS::JSON_FORMAT::ERROR_TITLE();
            }

            if (!f_sn) {
                flag = false;
                err[DB_CONSTANTS::JSON_FORMAT::SAVE_NAME] = DB_CONSTANTS::JSON_FORMAT::ERROR_SAVE_NAME();
            }

            if (!f_fp) {
                flag = false;
                err[DB_CONSTANTS::JSON_FORMAT::FILE_PATH] = DB_CONSTANTS::JSON_FORMAT::ERROR_FILE_PATH();
            }

            if (!f_s) {
                flag = false;
                err[DB_CONSTANTS::JSON_FORMAT::SUFFIX] = DB_CONSTANTS::JSON_FORMAT::ERROR_SUFFIX();
            }

            if (flag) {
                if (const auto url_f = CORE::MEDIA_INFO::cutURL(url); !add({userId, url_f, audio_code, video_code, video_format, title, save_name, file_path, suffix, 0, false, metadata, subtitles, auto_generated_subtitles})) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ADD_DOWNLOAD_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }

            else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
        }

        res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = err;

        return res;
    }

    QJsonObject DbManager::removeDownload(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (remove(userId)) res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;

            else {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::DATABASE_EMPTY();
            }
        }

        return res;
    }

    QJsonObject DbManager::removeAllDownloads() const {
        QJsonObject res;

        if (removeAll()) res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;

        else {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::DATABASE_EMPTY();
        }

        return res;
    }

    QJsonObject DbManager::updateAudioCode(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (const auto new_audio_code = obj[DB_CONSTANTS::JSON_FORMAT::AUDIO_CODE].toInt(); !CORE::MEDIA_INFO::ifValidAudioCode(new_audio_code)) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = CORE_CONSTANTS::MEDIA_I_TAGS::AUDIO_I_TAGS::ERROR_MESSAGE_I_TAG();
            }

            else {
                if (!DataBase::updateAudioCode(userId, new_audio_code)) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_AUDIO_CODE_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }
        }

        return res;
    }

    QJsonObject DbManager::updateVideoCode(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (const auto new_video_code = obj[DB_CONSTANTS::JSON_FORMAT::VIDEO_CODE].toInt(); !CORE::MEDIA_INFO::ifValidVideoCode(new_video_code)) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = CORE_CONSTANTS::MEDIA_I_TAGS::VIDEO_I_TAGS::ERROR_MESSAGE_I_TAG();
            }

            else {
                if (!DataBase::updateVideoCode(userId, new_video_code)) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_VIDEO_CODE_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }
        }

        return res;
    }

    QJsonObject DbManager::updateVideoFormat(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (const auto new_video_format = obj[DB_CONSTANTS::JSON_FORMAT::VIDEO_FORMAT].toString(); !CORE::MEDIA_INFO::ifValidVideoFormat(new_video_format)) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ERROR_VIDEO_FORMAT();
            }

            else {
                if (!DataBase::updateVideoFormat(userId, new_video_format)) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_VIDEO_FORMAT_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }
        }

        return res;
    }

    QJsonObject DbManager::updateSaveName(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (const auto new_save_name = obj[DB_CONSTANTS::JSON_FORMAT::SAVE_NAME].toString(); !CORE::MEDIA_INFO::ifValidSaveName(new_save_name)) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ERROR_SAVE_NAME();
            }

            else {
                if (!DataBase::updateSaveName(userId, new_save_name)) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_SAVE_NAME_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }
        }

        return res;
    }

    QJsonObject DbManager::updateFilePath(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (const auto new_file_path = obj[DB_CONSTANTS::JSON_FORMAT::FILE_PATH].toString(); !CORE::MEDIA_INFO::ifValidPath(new_file_path)) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ERROR_FILE_PATH();
            }

            else {
                if (!DataBase::updateFilePath(userId, new_file_path)) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_FILE_PATH_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }
        }

        return res;
    }

    QJsonObject DbManager::updateSuffix(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (const auto new_suffix = obj[DB_CONSTANTS::JSON_FORMAT::SUFFIX].toString(); !CORE::MEDIA_INFO::ifValidSuffix(new_suffix)) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ERROR_SUFFIX();
            }

            else {
                if (!DataBase::updateSuffix(userId, new_suffix)) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_SUFFIX_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }
        }

        return res;
    }

    QJsonObject DbManager::updateProgress(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (const auto new_progress = obj[DB_CONSTANTS::JSON_FORMAT::PROGRESS].toInt(); !CORE::MEDIA_INFO::ifValidProgress(new_progress)) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ERROR_PROGRESS();
            }

            else {
                if (!DataBase::updateProgress(userId, new_progress)) {
                    res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                    res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_PROGRESS_FAILED();
                }

                else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            }
        }

        return res;
    }

    QJsonObject DbManager::updateDownloadState(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (!DataBase::updateDownloadState(userId, obj[DB_CONSTANTS::JSON_FORMAT::DOWNLOAD_STATE].toBool())) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_DOWNLOAD_STATE_FAILED();
            }

            else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
        }

        return res;
    }

    QJsonObject DbManager::updateMetadata(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (!DataBase::updateMetadata(userId, obj[DB_CONSTANTS::JSON_FORMAT::METADATA].toBool())) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_METADATA_FAILED();
            }

            else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
        }

        return res;
    }

    QJsonObject DbManager::updateSubtitles(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (!DataBase::updateSubtitles(userId, obj[DB_CONSTANTS::JSON_FORMAT::SUBTITLES].toBool())) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_SUBTITLES_FAILED();
            }

            else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
        }

        return res;
    }

    QJsonObject DbManager::updateAutoGeneratedSubtitles(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            if (!DataBase::updateAutoGeneratedSubtitles(userId, obj[DB_CONSTANTS::JSON_FORMAT::AUTO_GENERATED_SUBTITLES].toBool())) {
                res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
                res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::UPDATE_AUTO_GENERATED_SUBTITLES_FAILED();
            }

            else res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
        }

        return res;
    }

    QJsonObject DbManager::readDownload(const QJsonObject& obj) const {
        QJsonObject res;

        if (const auto userId = obj[DB_CONSTANTS::JSON_FORMAT::USER_ID].toInt(); !ifExists(userId)) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::ID_NOT_EXISTS();
        }

        else {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            res[DB_CONSTANTS::JSON_FORMAT::PARAMETERS] = read(userId).toJson();
        }

        return res;
    }

    QJsonObject DbManager::readAllDownloads() const {
        QJsonObject res;

        if (isEmpty()) {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
            res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = DB_CONSTANTS::JSON_FORMAT::DATABASE_EMPTY();
        }

        else {
            res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_OK;
            res[DB_CONSTANTS::JSON_FORMAT::PARAMETERS] = CONTAINER::Download::toJsonList(readAll());
        }

        return res;
    }
}
