
#include "db/DbServer.hpp"

namespace DB {
    // Public

    DbServer::DbServer(QObject* parent) : QObject(parent), port(0) {
        this->handlers[Operation::VerifyState] = [this](const Request& req) {
            auto response = this->manager.isOpenDB();
            response[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
            sendResponse(req, response);
        };

        this->handlers[Operation::AddInformation] = [this](const Request& req) {
            auto response = this->manager.addDownload(req.params);
            response[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
            sendResponse(req, response);
        };

        this->handlers[Operation::DeleteInformation] = [this](const Request& req) {
            auto response = this->manager.removeDownload(req.params);
            response[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
            sendResponse(req, response);
        };

        this->handlers[Operation::DeleteAllInformation] = [this](const Request& req) {
            auto response = this->manager.removeAllDownloads();
            response[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
            sendResponse(req, response);
        };

        this->handlers[Operation::UpdateInformation] = [this](const Request& req) {
            QJsonObject response;

            switch (req.spec) {
                case Specification::AudioCode:
                    response = this->manager.updateAudioCode(req.params);
                    break;
                case Specification::VideoCode:
                    response = this->manager.updateVideoCode(req.params);
                    break;
                case Specification::VideoFormat:
                    response = this->manager.updateVideoFormat(req.params);
                    break;
                case Specification::SaveName:
                    response = this->manager.updateSaveName(req.params);
                    break;
                case Specification::FilePath:
                    response = this->manager.updateFilePath(req.params);
                    break;
                case Specification::Suffix:
                    response = this->manager.updateSuffix(req.params);
                    break;
                case Specification::Progress:
                    response = this->manager.updateProgress(req.params);
                    break;
                case Specification::DownloadState:
                    response = this->manager.updateDownloadState(req.params);
                    break;
                case Specification::Metadata:
                    response = this->manager.updateMetadata(req.params);
                    break;
                case Specification::Subtitles:
                    response = this->manager.updateSubtitles(req.params);
                    break;
                case Specification::AutoGeneratedSubtitles:
                    response = this->manager.updateAutoGeneratedSubtitles(req.params);
                    break;
                default:
                    break;
            }

            response[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
            sendResponse(req, response);
        };

        this->handlers[Operation::GetInformation] = [this](const Request& req) {
            auto response = this->manager.readDownload(req.params);
            response[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
            sendResponse(req, response);
        };

        this->handlers[Operation::GetAllInformation] = [this](const Request& req) {
            auto response = this->manager.readAllDownloads();
            response[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
            sendResponse(req, response);
        };
    }

    bool DbServer::start() {
        connect(&this->server, &QTcpServer::newConnection, this, &DbServer::onNewConnection);

        return this->server.listen(QHostAddress::LocalHost, 0);
    }

    int DbServer::getPort() const {return this->server.serverPort();}


    // Private Slots

    void DbServer::onNewConnection() {
        while (this->server.hasPendingConnections()) {
            const QTcpSocket* socket = this->server.nextPendingConnection();
            connect(socket, &QTcpSocket::readyRead, this, &DbServer::onReadyRead);
            connect(socket, &QTcpSocket::disconnected, socket, &QTcpSocket::deleteLater);
        }
    }

    void DbServer::onReadyRead() {
        auto* socket = qobject_cast<QTcpSocket*>(sender());

        if (!socket) return;

        while (socket->canReadLine()) {
            QJsonParseError err;

            auto data = socket->readLine();
            auto doc = QJsonDocument::fromJson(data, &err);

            if (err.error != QJsonParseError::NoError || !doc.isObject()) {
                sendError(socket, -1, DB_CONSTANTS::JSON_FORMAT::INVALID_JSON());
                continue;
            }

            auto obj = doc.object();

            const auto id = obj[DB_CONSTANTS::JSON_FORMAT::ID].toInt();
            const auto op = parseOperation(obj[DB_CONSTANTS::JSON_FORMAT::OPERATION].toString());
            const auto spec = parseSpecification(obj[DB_CONSTANTS::JSON_FORMAT::SPECIFICATION].toString());

            if (op == Operation::Unknown) sendError(socket, id, DB_CONSTANTS::JSON_FORMAT::INVALID_OPERATION());

            if (op == Operation::UpdateInformation && spec == Specification::Unknown) sendError(socket, id, DB_CONSTANTS::JSON_FORMAT::INVALID_SPECIFICATION());

            Request req {id, op, spec, obj[DB_CONSTANTS::JSON_FORMAT::PARAMETERS].toObject(), socket};

            if (this->handlers.contains(op)) this->handlers[op](req);
        }
    }


    // Private

    void DbServer::sendResponse(const Request& req, const QJsonObject& data) {
        if (!req.socket) return;
        data[DB_CONSTANTS::JSON_FORMAT::ID] = req.id;
        req.socket->write(QJsonDocument(data).toJson(QJsonDocument::Compact) + "\n");
    }

    void DbServer::sendError(QTcpSocket* socket, const int id, const QString& msg) {
        QJsonObject res;

        res[DB_CONSTANTS::JSON_FORMAT::ID] = id;
        res[DB_CONSTANTS::JSON_FORMAT::STATUS] = DB_CONSTANTS::JSON_FORMAT::STATUS_REFUSED;
        res[DB_CONSTANTS::JSON_FORMAT::MESSAGE] = msg;

        socket->write(QJsonDocument(res).toJson(QJsonDocument::Compact) + "\n");
    }
}
