
#pragma once

#include <QJsonObject>
#include <QMutex>

namespace CONTAINER {
    class Download final {
    public:
        Download();
        Download(int id, QString url, int audio_code, int video_code, QString video_format, QString title, QString save_name, QString file_path, QString suffix, bool metadata, bool subtitles, bool auto_generated_subtitles);
        Download(int id, QString url, int audio_code, int video_code, QString video_format, QString title, QString save_name, QString file_path, QString suffix, int progress, bool download_state, bool metadata, bool subtitles, bool auto_generated_subtitles);
        Download(const Download& other);
        Download& operator=(const Download& other);
        bool operator==(const Download& other) const;

        int getId() const;
        QString getUrl() const;
        int getAudioCode() const;
        int getVideoCode() const;
        QString getVideoFormat() const;
        QString getTitle() const;
        QString getSaveName() const;
        QString getFilePath() const;
        QString getSuffix() const;
        int getProgress() const;
        bool getDownloadState() const;
        bool getMetadata() const;
        bool getSubtitles() const;
        bool getAutoGeneratedSubtitles() const;

        void setAudioCode(int audioCode);
        void setVideoCode(int videoCode);
        void setVideoFormat(const QString &videoFormat);
        void setSaveName(const QString &saveName);
        void setFilePath(const QString &filePath);
        void setSuffix(const QString &suf);
        void setProgress(int prog);
        void setDownloadState(bool downloadState);
        void setMetadata(bool met);
        void setSubtitles(bool subt);
        void setAutoGeneratedSubtitles(bool autoGeneratedSubtitles);

        QJsonObject toJson() const;
        static Download fromJson(const QJsonObject& obj);
        static QJsonObject toJsonList(const QList<Download>& list);
        static QList<Download> fromJsonList(const QJsonObject& obj);

    private:
        mutable QMutex mutex;

        int id;
        QString url;
        int audio_code;
        int video_code;
        QString video_format;
        QString title;
        QString save_name;
        QString file_path;
        QString suffix;
        int progress;
        bool download_state;
        bool metadata;
        bool subtitles;
        bool auto_generated_subtitles;
    };

    inline QDataStream& operator<<(QDataStream& out, const Download& d) {
        out << d.getId() << d.getUrl() << d.getAudioCode() << d.getVideoCode() << d.getVideoFormat() << d.getTitle() << d.getSaveName() << d.getFilePath() << d.getSuffix() << d.getProgress() << d.getDownloadState() << d.getMetadata() << d.getSubtitles() << d.getAutoGeneratedSubtitles();
        return out;
    }

    inline QDataStream& operator>>(QDataStream& in, Download& d) {
        int id; int ac; int vc; int prog; bool ds; bool met; bool subt; bool atSubt;
        QString url; QString vf; QString tt; QString sn; QString fp; QString suf;

        in >> id >> url >> ac >> vc >> vf >> tt >> sn >> fp >> suf >> prog >> ds >> met >> subt >> atSubt;
        d = Download(id, url, ac, vc, vf, tt, sn, fp, suf, prog, ds, met, subt, atSubt);

        return in;
    }

    inline QDataStream& operator<<(QDataStream& out, const QSharedPointer<Download>& d) {
        const auto isNull = d.isNull();
        out << isNull;
        if (!isNull) out << *d;
        return out;
    }

    inline QDataStream& operator>>(QDataStream& in, QSharedPointer<Download>& d) {
        bool isNull;
        in >> isNull;

        if (isNull) d.clear();

        else {
            d = QSharedPointer<Download>::create();
            in >> *d;
        }

        return in;
    }
}
