
#pragma once

#include "container/Download.hpp"
#include <QSqlQuery>

namespace DB {
    class DataBase : public QObject {
        Q_OBJECT
    protected:
        explicit DataBase(QObject* parent = nullptr);
        [[nodiscard]] bool init();
        [[nodiscard]] bool isOpen() const;
        [[nodiscard]] bool isEmpty() const;
        [[nodiscard]] QString getPath() const;
        [[nodiscard]] bool ifExists(int id) const;
        [[nodiscard]] bool add(const CONTAINER::Download& d) const;
        [[nodiscard]] bool remove(int id) const;
        [[nodiscard]] bool removeAll() const;
        [[nodiscard]] bool updateAudioCode(int id, int audioCode) const;
        [[nodiscard]] bool updateVideoCode(int id, int videoCode) const;
        [[nodiscard]] bool updateVideoFormat(int id, const QString& videoFormat) const;
        [[nodiscard]] bool updateSaveName(int id, const QString& saveName) const;
        [[nodiscard]] bool updateFilePath(int id, const QString& filePath) const;
        [[nodiscard]] bool updateSuffix(int id, const QString& suffix) const;
        [[nodiscard]] bool updateProgress(int id, int progress) const;
        [[nodiscard]] bool updateDownloadState(int id, bool download_state) const;
        [[nodiscard]] bool updateMetadata(int id, bool metadata) const;
        [[nodiscard]] bool updateSubtitles(int id, bool subtitles) const;
        [[nodiscard]] bool updateAutoGeneratedSubtitles(int id, bool autoGeneratedSubtitles) const;
        [[nodiscard]] CONTAINER::Download read(int id) const;
        [[nodiscard]] QList<CONTAINER::Download> readAll() const;

    private:
        [[nodiscard]] bool createTable() const;
        QString dataBaseDir;
        QSqlDatabase db;
    };
}
