
#pragma once

#include "container/Download.hpp"
#include "db/Operation.hpp"
#include "db/Specification.hpp"
#include <QQueue>
#include <QTcpSocket>

namespace DB {
    class DbClient final : public QObject {
        Q_OBJECT
    public:
        explicit DbClient(quint16 port, QObject* parent = nullptr);
        void verifyState(std::function<void(QJsonObject)> cb);
        void addDownload(const CONTAINER::Download& download, std::function<void(QJsonObject)> cb);
        void removeDownload(int userId, std::function<void(QJsonObject)> cb);
        void removeAllDownloads(std::function<void(QJsonObject)> cb);
        void updateAudioCode(int userId, int audio_code, std::function<void(QJsonObject)> cb);
        void updateVideoCode(int userId, int video_code, std::function<void(QJsonObject)> cb);
        void updateVideoFormat(int userId, const QString& video_format, std::function<void(QJsonObject)> cb);
        void updateSaveName(int userId, const QString& saveName, std::function<void(QJsonObject)> cb);
        void updateFilePath(int userId, const QString& filePath, std::function<void(QJsonObject)> cb);
        void updateSuffix(int userId, const QString& suffix, std::function<void(QJsonObject)> cb);
        void updateProgress(int userId, int progress, std::function<void(QJsonObject)> cb);
        void updateDownloadState(int userId, bool download_state, std::function<void(QJsonObject)> cb);
        void updateMetadata(int userId, bool metadata, std::function<void(QJsonObject)> cb);
        void updateSubtitles(int userId, bool subtitles, std::function<void(QJsonObject)> cb);
        void updateAutoGeneratedSubtitles(int userId, bool auto_generated_subtitles, std::function<void(QJsonObject)> cb);
        void readDownload(int userId, std::function<void(QJsonObject)> cb);
        void readAllDownloads(std::function<void(QJsonObject)> cb);
        ~DbClient() override;

    private slots:
        void onReadyRead();

    private:
        struct Pending {
            Operation op;
            Specification spec;
            QJsonObject params;
            std::function<void(QJsonObject)> cb;
        };

        void connectToServer() const;
        void reconnect() const;
        void flushPending();
        void sendRequest(const Operation& op, const Specification& spec, const QJsonObject& params, std::function<void(QJsonObject)> cb);

        QTcpSocket* socket;
        quint16 port;
        inline static int nextId = 1;
        QMap<int, std::function<void(QJsonObject)>> callbacks;
        QQueue<Pending> pending;
    };
}
