
#pragma once

#include "db/DataBase.hpp"

namespace DB {
    class DbManager final : public DataBase {
    public:
        explicit DbManager(QObject *parent = nullptr);
        [[nodiscard]] QJsonObject isOpenDB() const;
        [[nodiscard]] QJsonObject addDownload(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject removeDownload(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject removeAllDownloads() const;
        [[nodiscard]] QJsonObject updateAudioCode(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateVideoCode(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateVideoFormat(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateSaveName(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateFilePath(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateSuffix(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateProgress(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateDownloadState(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateMetadata(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateSubtitles(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject updateAutoGeneratedSubtitles(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject readDownload(const QJsonObject& obj) const;
        [[nodiscard]] QJsonObject readAllDownloads() const;
    };
}
