
#pragma once

namespace DB {
    enum class Specification {
        AudioCode,
        VideoCode,
        VideoFormat,
        Title,
        SaveName,
        FilePath,
        Suffix,
        Progress,
        DownloadState,
        Metadata,
        Subtitles,
        AutoGeneratedSubtitles,
        Unknown
    };

    inline Specification parseSpecification(const QString& spec) {
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::AUDIO_CODE, Qt::CaseInsensitive) == 0) return Specification::AudioCode;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::VIDEO_CODE, Qt::CaseInsensitive) == 0) return Specification::VideoCode;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::VIDEO_FORMAT, Qt::CaseInsensitive) == 0) return Specification::VideoFormat;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::TITLE, Qt::CaseInsensitive) == 0) return Specification::Title;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::SAVE_NAME, Qt::CaseInsensitive) == 0) return Specification::SaveName;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::FILE_PATH, Qt::CaseInsensitive) == 0) return Specification::FilePath;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::SUFFIX, Qt::CaseInsensitive) == 0) return Specification::Suffix;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::PROGRESS, Qt::CaseInsensitive) == 0) return Specification::Progress;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::DOWNLOAD_STATE, Qt::CaseInsensitive) == 0) return Specification::DownloadState;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::METADATA, Qt::CaseInsensitive) == 0) return Specification::Metadata;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::SUBTITLES, Qt::CaseInsensitive) == 0) return Specification::Subtitles;
        if (spec.compare(DB_CONSTANTS::UPDATE_OPTIONS::AUTO_GENERATED_SUBTITLES, Qt::CaseInsensitive) == 0) return Specification::AutoGeneratedSubtitles;

        return Specification::Unknown;
    }

    inline QString specToString(const Specification& spec) {
        switch (spec) {
            case Specification::AudioCode: return DB_CONSTANTS::UPDATE_OPTIONS::AUDIO_CODE;
            case Specification::VideoCode: return DB_CONSTANTS::UPDATE_OPTIONS::VIDEO_CODE;
            case Specification::VideoFormat: return DB_CONSTANTS::UPDATE_OPTIONS::VIDEO_FORMAT;
            case Specification::Title: return DB_CONSTANTS::UPDATE_OPTIONS::TITLE;
            case Specification::SaveName: return DB_CONSTANTS::UPDATE_OPTIONS::SAVE_NAME;
            case Specification::FilePath: return DB_CONSTANTS::UPDATE_OPTIONS::FILE_PATH;
            case Specification::Suffix: return DB_CONSTANTS::UPDATE_OPTIONS::SUFFIX;
            case Specification::Progress: return DB_CONSTANTS::UPDATE_OPTIONS::PROGRESS;
            case Specification::DownloadState: return DB_CONSTANTS::UPDATE_OPTIONS::DOWNLOAD_STATE;
            case Specification::Metadata: return DB_CONSTANTS::UPDATE_OPTIONS::METADATA;
            case Specification::Subtitles: return DB_CONSTANTS::UPDATE_OPTIONS::SUBTITLES;
            case Specification::AutoGeneratedSubtitles: return DB_CONSTANTS::UPDATE_OPTIONS::AUTO_GENERATED_SUBTITLES;
            default: return DB_CONSTANTS::UPDATE_OPTIONS::UNKNOWN;
        }
    }
}
