
#pragma once

#include "constants/Ui_Constants.hpp"
#include <QComboBox>
#include <QDialog>
#include <QFormLayout>
#include <QGroupBox>
#include <QLabel>

namespace UI {
    class DownloadConfig final : public QDialog {
        Q_OBJECT
    public:
        inline static int nextId = UI_CONSTANTS::DOWNLOAD_CONFIG::DEFAULT_NEXT_ID;
        explicit DownloadConfig(QWidget* parent = nullptr);
        [[nodiscard]] int getId() const;
        void requestEdit(const CONTAINER::Download& download);

    private slots:
        void timer1Finished(const QString& text);
        void timer2Finished(const QString& audio_code);
        void timer3Finished(const QString& video_code);
        void timer4Finished(const QString& video_format);
        void showItagsBtnClicked() const;
        void modeComboChanged();
        void metComboChanged();
        //void subtComboChanged();
        //void atSubtComboChanged();
        void outputBtnClicked();
        void okBtnClicked();

    private:
        static void sleepForMilliseconds(int milliseconds);

        int idd;
        bool normalMode = true;
        bool askForSavePath = true;

        int id;
        QString url;
        QString title;
        bool ifAudio;
        int audioCode;
        int videoCode;
        QString videoFormat;
        int progress;
        bool downloadState;
        bool metadata;
        bool subtitles;
        bool autoGeneratedSubtitles;
        QString filePath;
        QString saveName;
        QString suffix;

        QVBoxLayout* mainLayout;

        QGroupBox* basicBox;
        QFormLayout* basicForm;
        QLabel* urlLab;
        QLineEdit* urlEdit;
        QTimer* timer1;
        QLabel* titleLab;
        QLineEdit* titleEdit;

        QGroupBox* modeBox;
        QFormLayout* modeForm;
        QLabel* modeLabel;
        QHBoxLayout* modeLayout;
        QComboBox* modeCombo;
        QPushButton* showITagsBtn;
        QLabel* audioLab;
        QLineEdit* audioEdit;
        QTimer* timer2;
        QLabel* videoLab;
        QLineEdit* videoEdit;
        QTimer* timer3;
        QLabel* nonStandardVideoLab;
        QLineEdit* nonStandardVideoEdit;
        QTimer* timer4;
        QLabel* metLab;
        QComboBox* metCombo;
        QLabel* subtLab;
        QComboBox* subtCombo;
        QLabel* at_subt_lab;
        QComboBox* at_subt_combo;

        QGroupBox* outputBox;
        QFormLayout* outputForm;
        QHBoxLayout* outputLayout;
        QLabel* outputLab;
        QLineEdit* outputEdit;
        QPushButton* outputBtn;
        QHBoxLayout* buttonLayout;
        QPushButton* okBtn;
    };
}
